version: '3'

services:
  postgres:
    container_name: go-microservice-boilerplate-api-postgres
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - go-microservice-boilerplate-api-postgres:/data/postgres
      - .docker/postgres/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
    restart: always
  mongo:
    container_name: go-microservice-boilerplate-api-mongo
    image: mongo
    restart: always
    volumes: 
      - go-microservice-boilerplate-api-mongo:/data/db
      - .docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - '27017:27017'
    env_file:
      - .env
  redis:
    container_name: go-microservice-boilerplate-api-redis
    image: 'redis:alpine'
    env_file:
      - .env
    volumes:
      - go-microservice-boilerplate-api-redis:/data
    ports:
      - 6379:6379

volumes:
  go-microservice-boilerplate-api-postgres:
  go-microservice-boilerplate-api-mongo:
  go-microservice-boilerplate-api-redis: